### ISSUE TITLE
NextAuth.js working with ZBD API for OAuth2

### ISSUE THREAD

**Issue by andrerfneves** [zebedeeio/next-auth-zbd-starter#1]
# Task

## General

We want to have a starter kit for a ZBD API + NextAuth.js flow such that it becomes trivial for folks to add ZBD Login to any NextJS applications they are building. To do so we must configure custom flows for `authorization`, `userinfo`, etc, in the NextAuth settings.

The starter template code repo has been setup here, and an initial custom provider settings has been created. **The goal of this task is to get this working 100%** such that NextAuth can easily work with ZBD API and we have source code to point users to.

## ZBD API

The following `client_id` and `client_secret` can be used:
**clientId**: f9efbdd2-5621-4bd6-aa3a-a5619179ddf5
**clientSecret**: 8f54c83f-323c-4e4c-838a-3c2792082c2b

The following `callbackUrl` have been setup on the ZBD API side of things, but happy to add/switch to anything necessary:
`http://localhost:3000/api/auth/zbd`

## Resources

- zbd.dev --> for all things ZBD API
  - https://zbd.dev/api-reference/oauth2/authorization
  - https://zbd.dev/api-reference/oauth2/fetch-access-token
  - https://zbd.dev/api-reference/oauth2/refresh-token
  - https://zbd.dev/api-reference/oauth2/get-user
  - https://zbd.dev/api-reference/oauth2/get-wallet
  - https://zbd.dev/docs/zbd-login/integration
- NextAuth
  - Demo: https://next-auth-example.vercel.app/
  - Custom OAuth2 Provider Docs: https://next-auth.js.org/configuration/providers/oauth#using-a-custom-provider

## Contact

@nirgal-soft @zantoshi and @andrerfneves can support in any questions / issues.

**Comment by rishi-raj-jain** [comment]
@andrerfneves I think you need to update the callback to /api/auth/callback/zbd instead

<img width="1160" alt="Screenshot 2023-09-28 at 7 34 37 AM" src="https://github.com/zebedeeio/next-auth-zbd-starter/assets/46300090/def6d3b6-ee2b-444d-82d2-420e50cce6dd">

**Comment by rishi-raj-jain** [comment]
Right now it's pointing to http://localhost:3000/api/auth/zbd.

**Comment by andrerfneves** [comment]
Ah nice catch. I just set it to both just in case:

<img width="430" alt="Screenshot 2023-09-27 at 7 06 43 PM" src="https://github.com/zebedeeio/next-auth-zbd-starter/assets/2574011/f14f26de-9122-4cf3-a7d0-9654a4adfeca">

**Comment by rishi-raj-jain** [comment]
Awesome!

**Comment by rishi-raj-jain** [comment]
<img width="1512" alt="Screenshot 2023-09-28 at 7 40 10 AM" src="https://github.com/zebedeeio/next-auth-zbd-starter/assets/46300090/e7ea11b4-07b2-46af-a4f9-94f3be8ad9e9">

For my user, it says OAuth2 not found when I try to log in, can you help there? What do I need to ZBD to find my OAuth2?

**Comment by andrerfneves** [comment]
Hmm, it's probably the scope that's incorrect? What `scope` are you passing?

**Comment by rishi-raj-jain** [comment]
scope: "user"

**Comment by rishi-raj-jain** [comment]
<img width="715" alt="Screenshot 2023-09-28 at 7 41 55 AM" src="https://github.com/zebedeeio/next-auth-zbd-starter/assets/46300090/2b8f9996-7894-4995-97c8-36ec3e0a2437">
Don't see any examples here to use anything other than "user"

**Comment by andrerfneves** [comment]
Can you try `scope` as `user wallet`?

**Comment by andrerfneves** [comment]
@vlimag any idea why this could be triggering error for this scope?

**Comment by rishi-raj-jain** [comment]
@andrerfneves 

Somehow I got 401 after the login issue was resolved.

**Comment by rishi-raj-jain** [comment]
<img width="1142" alt="Screenshot 2023-09-28 at 8 04 56 AM" src="https://github.com/zebedeeio/next-auth-zbd-starter/assets/46300090/d9fe71ba-1249-4239-957c-797d27296d60">

**Comment by andrerfneves** [comment]
I don't believe you need to pass an API Key on the header of the request to the ZBD API so that shouldn't be the issue. Hmmm

**Comment by rishi-raj-jain** [comment]
Sending in a recording

**Comment by rishi-raj-jain** [comment]
Hmmm seems like an API access issue tho. I'll be sending a recording in about 45 mins.

**Comment by rishi-raj-jain** [comment]
Or before if I get the errand done quickly.

**Comment by rockingrohit9639** [comment]
@andrerfneves can I also try this ?

**Comment by rishi-raj-jain** [comment]
Aight, I'm back

**Comment by rishi-raj-jain** [comment]
@andrerfneves can you give me a sample api key to test this with?

**Comment by andrerfneves** [comment]
@rockingrohit9639 we already have @rishi-raj-jain completing this. I will create other similar bounties that you can try.

**Comment by rishi-raj-jain** [comment]
So to fetch user info https://zbd.dev/api-reference/oauth2/get-user the apikey header is required

**Comment by rishi-raj-jain** [comment]
I created one from dashboard.z... and printed the access_token generated

**Comment by rishi-raj-jain** [comment]
<img width="1512" alt="Screenshot 2023-09-28 at 8 56 11 AM" src="https://github.com/zebedeeio/next-auth-zbd-starter/assets/46300090/90dcaecf-c580-4dc9-b882-6f5214093a59">

**Comment by rishi-raj-jain** [comment]
<img width="653" alt="Screenshot 2023-09-28 at 8 56 35 AM" src="https://github.com/zebedeeio/next-auth-zbd-starter/assets/46300090/3658ca29-ffe8-431c-b7d9-ac1cd8d70603">

and then put the values here but it fails

**Comment by andrerfneves** [comment]
Ah so you got a Live API Key from ZBD dashboard and it cleared? Needing API key for the user and wallet fetching endpoints make sense.

**Comment by andrerfneves** [comment]
Okay I need to have @vlimag help here

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 we already have @rishi-raj-jain completing this. I will create other similar bounties that you can try.

Ok thanks

**Comment by rishi-raj-jain** [comment]
<img width="1512" alt="Screenshot 2023-09-28 at 9 09 12 AM" src="https://github.com/zebedeeio/next-auth-zbd-starter/assets/46300090/8774a9ba-f691-4489-a192-62ee86c8c79c">
@andrerfneves can you approve my account? feel free to delete once this is done. Email with the account: rishi18304@iiitd.ac.in

**Comment by rishi-raj-jain** [comment]
<img width="643" alt="Screenshot 2023-09-28 at 9 09 49 AM" src="https://github.com/zebedeeio/next-auth-zbd-starter/assets/46300090/b9f17ff6-837e-466f-afdd-bee774967210">
this fails with what I get from the api key in the sandbox
<img width="1302" alt="Screenshot 2023-09-28 at 9 09 59 AM" src="https://github.com/zebedeeio/next-auth-zbd-starter/assets/46300090/bd7535a2-fc2d-4952-bff5-a89c63e965af">

**Comment by rishi-raj-jain** [comment]
<img width="1512" alt="Screenshot 2023-09-28 at 9 14 22 AM" src="https://github.com/zebedeeio/next-auth-zbd-starter/assets/46300090/4c6affd1-86ac-429d-b710-19bcef37a8de">

I think now you can approve it quickly

**Comment by andrerfneves** [comment]
Live API Key here: `TsKq6BWl28B3hEYUw0ZHTuvFpPa1n8PC`

Will try and get your user approved asap

**Comment by andrerfneves** [comment]
For the same project that uses the OAuth2 keys, so `the right project live API Key`

**Comment by rishi-raj-jain** [comment]
That worked wohooo!

**Comment by rishi-raj-jain** [comment]
now solving the user

**Comment by rishi-raj-jain** [comment]
<img width="1512" alt="Screenshot 2023-09-28 at 9 18 56 AM" src="https://github.com/zebedeeio/next-auth-zbd-starter/assets/46300090/264119a8-bb9d-41b2-bf72-57ba9f7dcb7f">

**Comment by rishi-raj-jain** [comment]
How do I get the name of the user? or I can ignore it?
<img width="606" alt="Screenshot 2023-09-28 at 9 20 51 AM" src="https://github.com/zebedeeio/next-auth-zbd-starter/assets/46300090/ddc42771-7f24-40d7-b226-b0011709051a">

**Comment by rishi-raj-jain** [comment]
Done! Creating PR
